# General Configuration
version: '{build}'

init:
  - ps: |
      If($Env:APPVEYOR_REPO_TAG -eq "true")
      {
        Write-Host "We now have a tagged release. Proper."
        Write-Host "Tag is $Env:APPVEYOR_REPO_TAG_NAME"
        $env:APPVEYOR_BUILD_VERSION=$env:APPVEYOR_REPO_TAG_NAME
        Update-AppveyorBuild -Version "$Env:APPVEYOR_REPO_TAG_NAME"
      } 
      else 
      {
        $releases = "https://api.github.com/repos/$env:APPVEYOR_REPO_NAME/releases"
        $tag = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].tag_name
        $spl = $tag.Split("-")[0]
        Update-AppveyorBuild -Version "$spl.$Env:APPVEYOR_BUILD_VERSION-wip"
      }
      Write-Host "Hello. Build version is: $Env:APPVEYOR_BUILD_VERSION"

# Environment Configuration
image: Visual Studio 2019
cache:
  - '%LocalAppData%\NuGet\v3-cache'

install:
  #init and update submodules
  - git submodule update --recursive --init

 # version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'

# Build Configuration
platform: Any CPU
configuration: Release

before_build:
  - nuget restore

build:  
  project: SpeckleCoreGeometry.sln
  verbosity: minimal

after_build:
  # remove garbage
  - ps: |
      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleCoreGeometry\bin\Release\net45\x86" -Recurse -ErrorAction Ignore
      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleCoreGeometry\bin\Release\net45\x64" -Recurse -ErrorAction Ignore
      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleCoreGeometry\bin\Release\net45\*.pdb" -Recurse -ErrorAction Ignore
      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleCoreGeometry\bin\Release\net45\SpeckleCoreGeometry.dll.config" -Recurse -ErrorAction Ignore
 # zip everything into a zip file containing package folder structure
 # currently only picking net45 stuff
  - 7z a SpeckleCoreGeometry.zip "%APPVEYOR_BUILD_FOLDER%\SpeckleCoreGeometry\bin\Release\net45\*"

artifacts:
  - path: SpeckleCoreGeometry.zip
    name: Release

#deploy to github
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: D5tPFvdQMg9sIe0sSvQjEWw4KAdOk1jyxNwiH5qP5DpDmUH6n6NgTdA+56vXS1Pe # your encrypted token from GitHub
    artifact: Release
    force_update: true
    on:              
      appveyor_repo_tag: true


